name: Nextcloud Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Restrict permissions for security
permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repo code
      - name: Check out repository
        uses: actions/checkout@v3

      # Install Docker Compose and curl
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose curl

      # Login to Docker Hub with secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build containers (in your case pulls official images)
      - name: Build containers
        run: docker-compose -f docker-compose.yml build

      # Start all services
      - name: Start stack
        run: docker-compose -f docker-compose.yml up -d

      # Check running containers
      - name: Check running containers
        run: docker-compose ps

      # Health check with verbose curl and extended retries
      - name: Health check Nextcloud
        run: |
          PORT=$(docker ps --filter "name=app" --format '{{.Ports}}' | grep -oE '[0-9]+->80/tcp' | cut -d'-' -f1)
          if [ -z "$PORT" ]; then
            echo "❌ Could not detect mapped host port for Nextcloud app"
            exit 1
          fi
          echo "ℹ️ Detected Nextcloud on host port $PORT"
          for i in {1..20}; do
            echo "Attempt $i: Checking Nextcloud HTTP response on port $PORT"
            HTTP_CODE=$(curl -m 30 -s -w "%{http_code}" -o /dev/null http://localhost:$PORT)
            echo "HTTP response code: $HTTP_CODE"
            if [ "$HTTP_CODE" = "200" ]; then
              echo "✅ Nextcloud is responding on port $PORT"
              exit 0
            fi
            echo "Waiting for Nextcloud to respond (10 sec wait)..."
            sleep 10
          done
          echo "❌ Nextcloud did not respond after 200 seconds"
          echo "===== DOCKER COMPOSE LOGS ====="
          docker-compose logs --no-color
          exit 1

      # Tag and push official nextcloud image to your Docker Hub namespace
      - name: Push Nextcloud image to Docker Hub
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/nextcloud:latest
          echo "Tagging image 'nextcloud' as $IMAGE_NAME"
          docker tag nextcloud $IMAGE_NAME
          echo "Pushing image $IMAGE_NAME to Docker Hub"
          docker push $IMAGE_NAME

      # Scan Docker image for high/critical vulnerabilities with Trivy
      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/nextcloud:latest
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          format: table

      # Tear down all running containers and networks
      - name: Tear down stack
        run: docker-compose -f docker-compose.yml down

