name: Nextcloud Docker CI

on:
  push:
    branches:
      - master  # change if your main branch has another name
  pull_request:
    branches:
      - master		

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # (Optional) If you need to pull private images from Docker Hub, uncomment:
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build containers
        run: docker-compose -f docker-compose.yml build

      - name: Start stack
        run: docker-compose -f docker-compose.yml up -d

      - name: Check running containers
        run: docker-compose ps

      - name: Tear down stack
        run: docker-compose -f docker-compose.yml down

