name: Nextcloud Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_stack:
    name: Test Docker Compose Stack
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Docker Compose stack
        run: docker-compose up -d

      - name: Wait for Nextcloud to be ready
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:12000 > /dev/null; then
              echo "✅ Nextcloud is up!"
              exit 0
            fi
            echo "Waiting for Nextcloud..."
            sleep 5
          done
          echo "❌ Nextcloud did not become ready in time."
          docker-compose logs
          exit 1

      - name: Check running containers
        run: docker-compose ps

      - name: Tear down stack
        run: docker-compose down -v

  image_scan:
    name: Scan Docker Images for CVEs
    runs-on: ubuntu-latest

    steps:
      - name: Scan Docker images with Trivy
        uses: aquasecurity/trivy-action@v0.11.2
        with:
          scan-type: image
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          image-ref: |
            mariadb:lts
            redis:alpine
            nextcloud
            caddy:latest

  secret_scan:
    name: Scan Repository for Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Gitleaks to detect secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: ""

