name: Nextcloud Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# 🔒 Limit token permissions
permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # 📥 Checkout repository
      - name: Check out repository
        uses: actions/checkout@v3

      # 📦 Install Docker Compose + curl
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose curl

      # 🔐 Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 🛠 Build containers from docker-compose.yml
      - name: Build containers
        run: docker-compose -f docker-compose.yml build

      # 🚀 Start stack
      - name: Start stack
        run: docker-compose -f docker-compose.yml up -d

      # ✅ Check running containers
      - name: Check running containers
        run: docker-compose ps

      # 🌐 Improved & verbose health check
      - name: Health check Nextcloud
        run: |
          PORT=$(docker ps --filter "name=app" --format '{{.Ports}}' | grep -oE '[0-9]+->80/tcp' | cut -d'-' -f1)
          if [ -z "$PORT" ]; then
            echo "❌ Could not detect mapped host port for Nextcloud app"
            exit 1
          fi
          echo "ℹ️ Detected Nextcloud on host port $PORT"
          for i in {1..20}; do
            echo "Attempt $i: Checking Nextcloud HTTP response on port $PORT"
            HTTP_CODE=$(curl -m 30 -s -w "%{http_code}" -o /dev/null http://localhost:$PORT)
            echo "HTTP response code: $HTTP_CODE"
            if [ "$HTTP_CODE" = "200" ]; then
              echo "✅ Nextcloud is responding on port $PORT"
              exit 0
            fi
            echo "Waiting for Nextcloud to respond (10 sec wait)..."
            sleep 10
          done
          echo "❌ Nextcloud did not respond after 200 seconds"
          echo "===== DOCKER COMPOSE LOGS ====="
          docker-compose logs --no-color
          exit 1

      # 📤 Push Nextcloud image to Docker Hub
      - name: Push Nextcloud image to Docker Hub
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/nextcloud:latest
          echo "Pushing Docker image $IMAGE_NAME"
          docker tag nextcloud $IMAGE_NAME
          docker push $IMAGE_NAME

      # 🛡 Scan for vulnerabilities using Trivy
      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/nextcloud:latest
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          format: table

      # 🧹 Tear down stack
      - name: Tear down stack
        run: docker-compose -f docker-compose.yml down

