kname: Nextcloud Docker CI

on:
  push:
    branches:
      - master  # or main, depending on your branch
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build containers
        run: docker-compose -f docker-compose.yml build

      - name: Start stack
        run: docker-compose -f docker-compose.yml up -d

      - name: Check running containers
        run: docker-compose ps

      - name: Tear down stack
        run: docker-compose -f docker-compose.yml down

